Make Bootable USB: Version 1.1 Release

diff --git a/makeBootableUSB b/makeBootableUSB
--- a/makeBootableUSB
+++ b/makeBootableUSB
@@ -1,6 +1,9 @@
 #	This script makes a bootable USB Drive from an ISO Image
 #	Author: Siddhant Rath
+#	Mail : sid@tamu.edu
 #	Date : APR 4 2016
+#	Version 1.0
+#	GIT : https://github.com/Siddhant-R/LinuxTools.git
 
 #local variables
 bold=$(tput bold)
@@ -13,12 +16,12 @@ BLOCK_BLUE='\e[44m'
 BLOCK_NORMAL='\e[49m'
 #Header
 printf "%b" "\n${BLOCK_BLUE}                    --- MAKE BOOTABLE USB ---                  ${BLOCK_NORMAL}\n"
-
+printf "%b" "Version 1.1 \nReport issues at https://github.com/Siddhant-R/LinuxTools\n"
 #Boot option
 if (($#<2))
 then
-printf "%b" "Error. Please pass path to usb stick as an argument.\n" >&2
-printf "%b" "Example Usage : makeBootableUSB sdb bootable.iso \n" >&2
+printf "%b" "Error. Please pass path to usb stick and ISO image as arguments.\n" >&2
+printf "%b" "Example Usage : ${bold}makeBootableUSB sdb bootable.iso \n${normal}" >&2
 exit 1
 fi
 
@@ -41,7 +44,7 @@ fi
  
 
 printf "%b" "\n${bold}PLEASE MAKE SURE YOU HAVE SELECTED THE CORRECT USB DEVICE:${normal} \n"
-printf "%b" "$USB_SEL\n"
+printf "%b" "$USB_SEL\n\n"
 printf "%b" "${RED}${bold}!WARNING! '$1'${normal}${RED} will be EREASED and FORMATTED \n"
 printf "%b" "${NC}${bold}Do you want to continue? (yes/no):${normal} "
 
@@ -50,7 +53,7 @@ read makeBootableUSB_choice
 printf "%b" "$makeBootableUSB_choice"
 
 if [ "$makeBootableUSB_choice" != "yes" ]; then
-printf "%b" "\nExiting .... \nPlease Restart with proper drive\n"
+printf "%b" "\nExiting .... \n"
 exit 2
 fi
 
@@ -85,4 +88,6 @@ if(($?!=0))
  exit 1
 fi
 printf "%b" "${GREEN} [SUCCESS]${NC} \n"
+printf "%b" "Thank you for using Make Bootable USB.\n"
+printf "%b" "Find other useful tools at  https://github.com/Siddhant-R/LinuxTools\n"
 exit 0
